(define (problem hanoi0)
  (:domain hanoi)
  (:objects peg1 peg2 peg3 peg4 - peg d1 d2 - disc)
  (:init
   (smaller peg1 d1) (smaller peg1 d2)
   (smaller peg2 d1) (smaller peg2 d2)
   (smaller peg3 d1) (smaller peg3 d2)
   (smaller peg4 d1) (smaller peg4 d2)
   (smaller d2 d1)
   (clear peg2) (clear peg3) (clear peg4) (clear d1)
   (on d2 peg1) (on d1 d2)
   (base-peg peg1 peg1) (base-peg d1 peg1) (base-peg d2 peg1)
   (base-peg peg2 peg2)
   (base-peg peg3 peg3)
   (base-peg peg4 peg4)
   (= (total-cost) 0)

   (= (move-cost peg1 peg2) 1)
   (= (move-cost peg1 peg3) 1)
   (= (move-cost peg1 peg4) 2)

   (= (move-cost peg2 peg1) 1)
   (= (move-cost peg2 peg3) 1)
   (= (move-cost peg2 peg4) 2)

   (= (move-cost peg3 peg1) 1)
   (= (move-cost peg3 peg2) 1)
   (= (move-cost peg3 peg4) 2)

   (= (move-cost peg4 peg1) 2)
   (= (move-cost peg4 peg2) 2)
   (= (move-cost peg4 peg3) 2)
  )
  (:goal (and (on d2 peg3) (on d1 d2)))
  (:metric minimize (total-cost))
)
